StringTable {
 ItemClassName "CustomStringTableItem"
 Items {
  CustomStringTableItem "{65F925973591BB24}" {
   Id "BA_RadioInputs-frequency_page_down"
   Target_en_us "Page Frequency (Down)"
   Target_fr_fr "Réduire la fréquence (grand pas)"
   Target_it_it "Diminuisci frequenza (passo grande)"
   Target_de_de "Frequenz verringern (großer Schritt)"
   Target_es_es "Bajar frecuencia (salto grande)"
   Target_cs_cz "Snížit frekvenci (velký krok)"
   Target_pl_pl "Zmniejsz częstotliwość (duży skok)"
   Target_ru_ru "Уменьшить частоту (большой шаг)"
   Target_ja_jp "周波数を下げる （大きく）"
   Target_ko_kr "주파수 감소 (큰 단계)"
   Target_pt_br "Diminuir frequência (grande passo)"
   Target_zh_cn "降低频率 （大步进）"
   Target_uk_ua "Зменшити частоту (великий крок)"
   Status DEVELOPMENT_DONE
   Modified 1710829168
   Author "kylep"
   LastChanged "kylep"
  }
  CustomStringTableItem "{65F925960C2BC660}" {
   Id "BA_RadioInputs-frequency_page_up"
   Target_en_us "Page Frequency (Up)"
   Target_fr_fr "Augmenter la fréquence (grand pas)"
   Target_it_it "Aumenta frequenza (passo grande)"
   Target_de_de "Frequenz erhöhen (großer Schritt)"
   Target_es_es "Subir frecuencia (salto grande)"
   Target_cs_cz "Zvýšit frekvenci (velký krok)"
   Target_pl_pl "Zwiększ częstotliwość (duży skok)"
   Target_ru_ru "Увеличить частоту (большой шаг)"
   Target_ja_jp "周波数を上げる （大きく）"
   Target_ko_kr "주파수 증가 (큰 단계)"
   Target_pt_br "Aumentar frequência (grande passo)"
   Target_zh_cn "提高频率 （大步进）"
   Target_uk_ua "Збільшити частоту (великий крок)"
   Status DEVELOPMENT_DONE
   Modified 1710829175
   Author "kylep"
   LastChanged "kylep"
  }
  CustomStringTableItem "{6624E637FA760AFA}" {
   Id "BA_RadioInputs-VON_Transmitting_Channel0"
   Target_en_us "Transmit on channel 1"
   Target_fr_fr "Transmettre sur le canal 1"
   Target_it_it "Trasmetti sul canale 1"
   Target_de_de "Auf Kanal 1 senden"
   Target_es_es "Transmitir en el canal 1"
   Target_cs_cz "Vysílat na kanálu 1"
   Target_pl_pl "Nadawaj na kanale 1"
   Target_ru_ru "Передавать на канале 1"
   Target_ja_jp "チャンネル1で送信する"
   Target_ko_kr "채널 1에서 송신하기"
   Target_pt_br "Transmitir no canal 1"
   Target_zh_cn "在频道1上发射"
   Target_uk_ua "Передавати на каналі 1"
   Status DEVELOPMENT_DONE
   Modified 1713694593
   Author "kylep"
   LastChanged "kylep"
  }
  CustomStringTableItem "{6624E6373FCC952F}" {
   Id "BA_RadioInputs-VON_Transmitting_Channel1"
   Target_en_us "Transmit on channel 2"
   Target_fr_fr "Transmettre sur le canal 2"
   Target_it_it "Trasmetti sul canale 2"
   Target_de_de "Auf Kanal 2 senden"
   Target_es_es "Transmitir en el canal 2"
   Target_cs_cz "Vysílat na kanálu 2"
   Target_pl_pl "Nadawaj na kanale 2"
   Target_ru_ru "Передавать на канале 2"
   Target_ja_jp "チャンネル2で送信する"
   Target_ko_kr "채널 2에서 송신하기"
   Target_pt_br "Transmitir no canal 2"
   Target_zh_cn "在频道2上发射"
   Target_uk_ua "Передавати на каналі 2"
   Status DEVELOPMENT_DONE
   Modified 1713694696
   Author "kylep"
   LastChanged "kylep"
  }
 }
}