StringTable {
 ItemClassName "CustomStringTableItem"
 Items {
  CustomStringTableItem "{65F925973591BB24}" {
   Id "BA_RadioInputs-frequency_page_down"
   Target_en_us "Page Frequency (Down)"
   Target_fr_fr "Réduire la fréquence (grand pas)"
   Target_it_it "Diminuisci frequenza (passo grande)"
   Target_de_de "Frequenz verringern (großer Schritt)"
   Target_es_es "Bajar frecuencia (salto grande)"
   Target_cs_cz "Snížit frekvenci (velký krok)"
   Target_pl_pl "Zmniejsz częstotliwość (duży skok)"
   Target_ru_ru "Уменьшить частоту (большой шаг)"
   Target_ja_jp "周波数を下げる （大きく）"
   Target_ko_kr "주파수 감소 (큰 단계)"
   Target_pt_br "Diminuir frequência (grande passo)"
   Target_zh_cn "降低频率 （大步进）"
   Target_uk_ua "Зменшити частоту (великий крок)"
   Status DEVELOPMENT_DONE
   Modified 1710829168
   Author "kylep"
   LastChanged "kylep"
  }
  CustomStringTableItem "{65F925960C2BC660}" {
   Id "BA_RadioInputs-frequency_page_up"
   Target_en_us "Page Frequency (Up)"
   Target_fr_fr "Augmenter la fréquence (grand pas)"
   Target_it_it "Aumenta frequenza (passo grande)"
   Target_de_de "Frequenz erhöhen (großer Schritt)"
   Target_es_es "Subir frecuencia (salto grande)"
   Target_cs_cz "Zvýšit frekvenci (velký krok)"
   Target_pl_pl "Zwiększ częstotliwość (duży skok)"
   Target_ru_ru "Увеличить частоту (большой шаг)"
   Target_ja_jp "周波数を上げる （大きく）"
   Target_ko_kr "주파수 증가 (큰 단계)"
   Target_pt_br "Aumentar frequência (grande passo)"
   Target_zh_cn "提高频率 （大步进）"
   Target_uk_ua "Збільшити частоту (великий крок)"
   Status DEVELOPMENT_DONE
   Modified 1710829175
   Author "kylep"
   LastChanged "kylep"
  }
 }
}